config/routes.rb
CompApp::Application.routes.draw do
  get "blacklist_pages/blacklist"
  get "blacklist_pages/motherboard"
  get "blacklist_pages/cpu"
  get "blacklist_pages/ram"
  get "blacklist_pages/gpu"
  get "blacklist_pages/hd"
  get "blacklist_pages/power"
  get "blacklists/delete_mobo"
  get "blacklists/delete_cpu"
  get "blacklists/delete_ram"
  get "blacklists/delete_gpu"
  get "blacklists/delete_hd"
  get "blacklists/delete_power"
  post '/rate' => 'rater#create', :as => 'rate'
  get "computers/new"
  get "computers/current"
  get "computers/rename"
  get "computers/summary"
  get "computers/publish"
  get "computers/delete"

  get "similar_computers/menu"
  get "similar_computers/similar_price"
  get "similar_computers/similar_components"

  get "computers/delete_mobo"
  get "computers/delete_cpu"
  get "computers/delete_gpu"
  get "computers/delete_ram"
  get "computers/delete_hd"
  get "computers/delete_power"
  get "component_pages/cpu"
  get "component_pages/ram"
  get "component_pages/motherboard"
  get "build_by/price_option"
  get "build_by/select_price"
  post "build_by/select_price" => 'build_by#update'

  get "users/edit"
  get "users/new"
  get "users/index"
  get "component_pages/index"
  get "component_pages/gpu"
  get "component_pages/hd"
  get "component_pages/power"
  get "parts/add"
  get "parts/add_motherboard"
  post "parts/add_motherboard" => 'parts#create_motherboard'
  get "parts/add_cpu"
  post "parts/add_cpu" => 'parts#create_cpu'
  get "parts/add_gpu"
  post "parts/add_gpu" => 'parts#create_gpu'
  get "parts/add_ram"
  post "parts/add_ram" => 'parts#create_ram'
  get "parts/add_hd"
  post "parts/add_hd" => 'parts#create_hd'
  get "parts/add_power"
  post "parts/add_power" => 'parts#create_power'
  get "static_pages/home"
  get "static_pages/help"
  root "static_pages#home" #added this route to set the new home to static_pages#home
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :blacklists
  resources :users
  resources :computers

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper_method :update_notifications

  def home
  	if logged_in?
  		@computers = Computer.where(user_id: current_user.id)
  		@current_comp = Computer.find_by_id(current_user.current_comp)
  		@motherboards = Motherboard.where(creator: current_user.id)
  		@cpus = Cpu.where(creator: current_user.id)
  		@gpus = Gpu.where(creator: current_user.id)
  		@rams = Ram.where(creator: current_user.id)
  		@hds = Hd.where(creator: current_user.id)
  		@powers = Power.where(creator: current_user.id)
      @notifs = Notification.all
  	end
  end

  def update_notifications
    @user = current_user
    @user.notifications = @user.notifications + 1
    @user.save(validate: false)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<body data-no-turbolink>
<center><% if logged_in? %>
<%= link_to edit_user_path(current_user), class: "btn btn-lg btn-primary" do %>
<span class="glyphicon glyphicon-wrench"></span> Edit User Info
<% end %>
<%= link_to blacklist_pages_blacklist_path, class: "btn btn-lg btn-primary" do %>
<span class="glyphicon glyphicon-thumbs-down"></span> Blacklist Parts
<% end %>
<%= link_to users_path, class: "btn btn-default btn-lg" do %>
<span class="glyphicon glyphicon-globe"></span> View All Users
<% end %>
<%= link_to logout_path, method: "delete", class: "btn btn-lg btn-primary" do %>
<span class="glyphicon glyphicon-remove"></span> Log out
<% end %></center>

<% @notifs.each do |f| %>
  <% if current_user.notifications <= f.id %>
    <div>
      <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <center>
          <%= f.body %>
        </center>
        <% update_notifications %>
      </div>
    </div>
  <% end %>
<% end %>

<center><%= image_tag("logo.png") %></center>
	<center><h3>User: <%= current_user.name %> </h3></center>
	<center><h3>Email: <%= current_user.email %></h3><center>
    <center><h3>Your Computers</h3><center>
        <div class=" center jumbotron">
			  <table class="table", style="width:80%;vertical-align:top">
      <tr class="active">
        <th>Switch</th>
        <th><center>ID</center></th>
        <th><center>Name</center></th>
        <th><center>Price</center></th>
        <th><center>Delete</center></th>
      </tr>
      <% @computers.each do |f| %>
        <tr>
          <td>
          	<%if current_user.current_comp != f.id%>
          		<%= link_to "Make Current", computers_current_path(id:f.id)%>
          	<%end%>
          </td>
          <td><%= f.id %></td>
          <td><%= f.name %></td>
          <td>$<%= f.price %></td>
          <td>
            <%if current_user.current_comp != f.id%>
              <%= link_to "Delete", computers_delete_path(id:f.id), data: {confirm: "Really delete this computer?"}%>
            <%end%>
          </td>
        </tr>
       <%end%>
        <tr>
        	<td><%=link_to computers_new_path, class: "btn btn-lg btn-success" do %>
        		<strong>Create new Comp!</strong>
        		<%end%>
        	</td>
        	<td>
            <% if @current_comp.nil? %>
              <%=link_to computers_rename_path, class: "btn btn-lg btn-primary disabled" do %>
              Rename Current Computer
              <%end%>
            <% else %>
              <%=link_to computers_rename_path, class: "btn btn-lg btn-primary" do %>
              Rename Current Computer
              <%end%>
            <% end %>
        	</td>
        	<td>
            <% if @current_comp.nil? %>
              <%=link_to similar_computers_menu_path, class: "btn btn-lg btn-primary disabled" do %>
              View Similar Computers
              <%end%>
            <% else %>
              <%=link_to similar_computers_menu_path, class: "btn btn-lg btn-primary" do %>
              View Similar Computers
              <%end%>
            <% end %>
            </td>
            <td>
              <% if @current_comp.nil? %>
              <%=link_to computers_summary_path, class: "btn btn-lg btn-primary disabled" do %>
              View Current Computer
              <%end%>
            <% else %>
              <%=link_to computers_summary_path, class: "btn btn-lg btn-primary" do %>
              View Current Computer
              <%end%>
              <%end%>
            </td>
        </tr>
      </table>
      </div>

      <center><h3>Your Parts</h3></center>
      <div class="jumbotron">
        <br>
        <center><h5>Motherboards</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>CPU Type</center></th>
            <th><center>GPU Type</center></th>
            <th><center>RAM Type</center></th>
            <th><center>HD Type</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @motherboards.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.cpu_compad %></td>
              <td><%= f.gpu_compad %></td>
              <td><%= f.ram_compad %></td>
              <td><%= f.hd_compad %></td>
              <td><%= f.watts %></td>
              <td>$<%= f.price %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>CPUs</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          </thead>
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>Cores</center></th>
            <th><center>Speed</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @cpus.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.cores %></td>
              <td><%= f.speed %> GHz</td>
              <td><%= f.watts %></td>
              <td>$<%= f.price %></td>
            </tr>
          <% end %>
        </table>


        <center><h5>GPUs</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>VRAM</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @gpus.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.vram %> GB</td>
              <td><%= f.watts %></td>
              <td>$<%= f.price %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>RAM</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>Size</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @rams.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.size %> GB</td>
              <td><%= f.watts %></td>
              <td>$<%= f.price %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>HDs</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>Size</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @hds.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.size %> GB</td>
              <td><%= f.watts %></td>
              <td>$<%= f.price %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>Power Supplies</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @powers.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
            </tr>
          <% end %>
        </table>

      <br>
      <div>
        <%= link_to "Create a Part", parts_add_path, class: "btn btn-lg btn-success" %>
      </div>
    </div>

<% else %>
<center><%= image_tag("logo.png") %></center><br>
	<div class="center jumbotron">
		<center><h3>Welcome to Build a Comp!</h3></center>

		<center>
			<%= link_to users_new_path, class: "btn btn-lg btn-primary" do %>
				<span class="glyphicon glyphicon-plus"></span> Sign Up
			<% end %>
			<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
			<%= link_to login_path, class: "btn btn-lg btn-primary" do %>
				<span class="glyphicon glyphicon-user"></span> Log In
			<% end %>
		</center>
	</div>
<% end %>
</body>