config/routes.rb
CompApp::Application.routes.draw do
  get "blacklist_pages/blacklist"
  get "blacklist_pages/motherboard"
  get "blacklist_pages/cpu"
  get "blacklist_pages/ram"
  get "blacklist_pages/gpu"
  get "blacklist_pages/hd"
  get "blacklist_pages/power"
  get "blacklists/delete_mobo"
  get "blacklists/delete_cpu"
  get "blacklists/delete_ram"
  get "blacklists/delete_gpu"
  get "blacklists/delete_hd"
  get "blacklists/delete_power"
  post '/rate' => 'rater#create', :as => 'rate'
  get "computers/new"
  get "computers/current"
  get "computers/rename"
  get "computers/summary"
  get "computers/publish"
  get "computers/delete"

  get "similar_computers/menu"
  get "similar_computers/similar_price"
  get "similar_computers/similar_components"

  get "computers/delete_mobo"
  get "computers/delete_cpu"
  get "computers/delete_gpu"
  get "computers/delete_ram"
  get "computers/delete_hd"
  get "computers/delete_power"
  get "component_pages/cpu"
  get "component_pages/ram"
  get "component_pages/motherboard"
  get "build_by/price_option"
  get "build_by/select_price"
  post "build_by/select_price" => 'build_by#update'

  get "users/edit"
  get "users/new"
  get "users/index"
  get "component_pages/index"
  get "component_pages/gpu"
  get "component_pages/hd"
  get "component_pages/power"
  get "parts/add"
  get "parts/add_motherboard"
  post "parts/add_motherboard" => 'parts#create_motherboard'
  get "parts/add_cpu"
  post "parts/add_cpu" => 'parts#create_cpu'
  get "parts/add_gpu"
  post "parts/add_gpu" => 'parts#create_gpu'
  get "parts/add_ram"
  post "parts/add_ram" => 'parts#create_ram'
  get "parts/add_hd"
  post "parts/add_hd" => 'parts#create_hd'
  get "parts/add_power"
  post "parts/add_power" => 'parts#create_power'
  get "static_pages/home"
  get "static_pages/help"
  root "static_pages#home" #added this route to set the new home to static_pages#home
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :blacklists
  resources :users
  resources :computers

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  def add_motherboard
    @motherboard = Motherboard.new
  end

  def add_cpu
    @cpu = Cpu.new
  end

  def add_gpu
    @gpu = Gpu.new
  end

  def add_ram
    @ram = Ram.new
  end

  def add_hd
    @hd = Hd.new
  end

  def add_power
    @power = Power.new
  end

  def create_motherboard
    if @motherboard = Motherboard.create(motherboard_params)
      else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
    @motherboard.creator ||= current_user.id
    if @motherboard.save
      flash[:success] = "Your motherboard has been created!"
      @notif = Notification.create()
      @notif.body = "New part added! Part: Motherboard Creator: " + @motherboard.creator.to_s + " Name: " + @motherboard.name.to_s +
        " CPU Compatibility: " + @motherboard.cpu_compad.to_s + " GPU Compatibility: " + @motherboard.gpu_compad.to_s +
        " RAM Compatibility: " + @motherboard.ram_compad.to_s + " HD Compability: " + @motherboard.hd_compad.to_s +
        " Watts: " + @motherboard.watts.to_s + " Price: $" + @motherboard.price.to_s
      @notif.save
      redirect_to parts_add_path
    else
      flash[:danger] = "You must have the input of the correct type in all fields to create a part."
      redirect_to :back
    end
  end

  def create_cpu
    if @cpu = Cpu.create(cpu_params)
    else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
    @cpu.creator ||= current_user.id
    if @cpu.save
      flash[:success] = "Your CPU has been created!"
      @notif = Notification.create()
      @notif.body = "New part added! Part: CPU Creator: " + @cpu.creator.to_s + " Name: " + @cpu.name.to_s +
        " Motherboard Compatibility: " + @cpu.mb_compad.to_s + " Cores: " + @cpu.cores.to_s + 
        " Speed: " + @cpu.speed.to_s + " Watts: " + @cpu.watts.to_s + " Price: $" + @cpu.price.to_s
      @notif.save
      redirect_to parts_add_path
    else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
  end

  def create_gpu
    if @gpu = Gpu.create(gpu_params)
      else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
    @gpu.creator ||= current_user.id
    if @gpu.save
      flash[:success] = "Your GPU has been created!"
      @notif = Notification.create()
      @notif.body = "New part added! Part: GPU Creator: " + @gpu.creator.to_s + " Name: " + @gpu.name.to_s +
        " Motherboard Compatibility: " + @gpu.mb_compad.to_s + " VRAM: " + @gpu.vram.to_s + " Watts: " + 
        @gpu.watts.to_s + " Price: $" + @gpu.price.to_s
      @notif.save
      redirect_to parts_add_path
    else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
  end

  def create_ram
    if @ram = Ram.create(ram_params)
      else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
    @ram.creator ||= current_user.id
    if @ram.save
      flash[:success] = "Your RAM has been created!"
      @notif = Notification.create()
      @notif.body = "New part added! Part: RAM Creator: " + @ram.creator.to_s + " Name: " + @ram.name.to_s +
        " Motherboard Compatibility: " + @ram.mb_compad.to_s + " Size: " + @ram.size.to_s + " Watts: " + 
        @ram.watts.to_s + " Price: $" + @ram.price.to_s
      @notif.save
      redirect_to parts_add_path
    else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
  end

  def create_hd
    if @hd = Hd.create(hd_params)
      else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
    @hd.creator ||= current_user.id
    if @hd.save
      flash[:success] = "Your HD has been created!"
      @notif = Notification.create()
      @notif.body = "New part added! Part: HD Creator: " + @hd.creator.to_s + " Name: " + @hd.name.to_s +
        " Motherboard Compatibility: " + @hd.mb_compad.to_s + " Size: " + @hd.size.to_s + " Watts: " + 
        @hd.watts.to_s + " Price: $" + @hd.price.to_s
      @notif.save
      redirect_to parts_add_path
    else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
  end

  def create_power
    if @power = Power.create(power_params)
      else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
    @power.creator ||= current_user.id
    if @power.save
      flash[:success] = "Your power supply has been created!"
      @notif = Notification.create()
      @notif.body = "New part added! Part: Power Supply Creator: " + @power.creator.to_s + " Name: " + 
      @power.name.to_s + " Watts: " + @power.watts.to_s + " Price: $" + @power.price.to_s
      @notif.save
      redirect_to parts_add_path
    else
      flash[:danger] = "You must have input of the correct type in all fields to create a part."
      redirect_to :back
    end
  end

  private

  def motherboard_params
    params.require(:motherboard).permit(:price, :cpu_compad, :gpu_compad, :ram_compad, :hd_compad, :watts, :name)
  end

  def cpu_params
    params.require(:cpu).permit(:speed, :price, :mb_compad, :cores, :watts, :name, :creator)
  end

  def gpu_params
    params.require(:gpu).permit(:vram, :price, :mb_compad, :watts, :name, :creator)
  end

  def ram_params
    params.require(:ram).permit(:price, :size, :mb_compad, :watts, :name, :creator)
  end

  def hd_params
    params.require(:hd).permit(:price, :size, :mb_compad, :watts, :name, :creator)
  end

  def power_params
    params.require(:power).permit(:price, :watts, :name, :creator)
  end

end

app/views/parts/add.html.erb
<% provide(:title, 'Add A Part') %>

<center><h1>Select Type of Part to Add</h1></center>

<div class="center jumbotron">
    <center>
        <%= link_to "Motherboard", parts_add_motherboard_path, class: "btn btn-large btn-primary" %>
        <%= link_to "CPU", parts_add_cpu_path, class: "btn btn-large btn-primary" %>
        <%= link_to "GPU", parts_add_gpu_path, class: "btn btn-large btn-primary" %>
        <%= link_to "RAM", parts_add_ram_path, class: "btn btn-large btn-primary" %>
        <%= link_to "HD", parts_add_hd_path, class: "btn btn-large btn-primary" %>
        <%= link_to "Power Supply", parts_add_power_path, class: "btn btn-large btn-primary" %>

    </center>
    <br>
    <br>
    <center>
        <%= link_to static_pages_home_path, class: "btn btn-lg btn-primary" do %>
        <span class="glyphicon glyphicon-home"></span> Home
        <% end %>
    </center>
</div>

app/views/parts/add_cpu.html.erb
<% provide(:title, 'Add A CPU') %>

<center><h1>Add A CPU</h1></center>
<center><%= image_tag("cpu.png") %></center>
<center><p>-Central Processing Unit-</p></center>
<center><p>The hardware within a computer that carries out the instructions of a computer program.</p></center>
<center><p> It performs the basic arithmetical, logical, control and input/output operations of the system.</p></center>

<div class="row center jumbotron" >
  <div class="col-md-4 col-md-offset-4">

		<%= form_for :cpu do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control',:placeholder => "Name" %>

		<%= f.label :price , "Price ($)" %>
		<%= f.number_field :price, class: 'form-control',:placeholder => "0" %>

		<%= f.label :cores %>
		<%= f.number_field :cores, class: 'form-control',:placeholder => "0" %>

		<%= f.label :speed, "Speed (GHz)" %>
		<%= f.text_field :speed, class: 'form-control',:placeholder => "0.0" %>

		<%= f.label :mb_compad, "Motherboard Compatability" %>
		<%= f.radio_button :mb_compad, "AMD", class: 'form-control' %>	<center><%= label_tag :mb_compad_amd, "AMD" %></center>
		<%= f.radio_button :mb_compad, "Intel", class: 'form-control' %> <center><%= label_tag :mb_compad_intel, "Intel" %></center>	

		<%= f.label :watts %>
		<%= f.number_field :watts, class: 'form-control',:placeholder => "0" %>

		<br/>
		<br/>
		<center>
				<%= f.submit "Create CPU", class: "btn btn-lg btn-success" %>
				<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
				<%= link_to parts_add_path, class: "btn btn-lg btn-danger" do %> Cancel
				<% end %>
		</center>
    <% end %>
  </div>
</div>

app/views/parts/add_gpu.html.erb
<% provide(:title, 'Add A GPU') %>

<center><h1>Add A GPU</h1></center>
<br>
<center><%= image_tag("gpu.png") %></center>
<br>
<center><p>-Graphics Processing Unit-</p></center>
<center><p>A specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer intended for output to a display. </p></center>

<div class="row center jumbotron" >
  <div class="col-md-4 col-md-offset-4">

		<%= form_for :gpu do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control',:placeholder => "Name" %>

		<%= f.label :price , "Price ($)" %>
		<%= f.number_field :price, class: 'form-control',:placeholder => "0" %>

		<%= f.label :vram, "VRAM (GB)" %>
		<%= f.number_field :vram, class: 'form-control',:placeholder => "0" %>

		<%= f.label :mb_compad, "Motherboard Compatability" %>
		<%= f.radio_button :mb_compad, "PCI 3.0", class: 'form-control' %>	<center><%= label_tag :mb_compad_pci_3, "PCI 3.0" %></center>
		<%= f.radio_button :mb_compad, "PCI 3.0 x16", class: 'form-control' %>	<center><%= label_tag :mb_compad_pci_3_16, "PCI 3.0 x16" %></center>
		<%= f.radio_button :mb_compad, "PCI 2.0 x16", class: 'form-control' %>	<center><%= label_tag :mb_compad_pci_2_16, "PCI 2.0 x16" %></center>

		<%= f.label :watts %>
		<%= f.number_field :watts, class: 'form-control',:placeholder => "0" %>

		<br/>
		<br/>
		<center>
				<%= f.submit "Create GPU", class: "btn btn-lg btn-success" %>
				<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
				<%= link_to parts_add_path, class: "btn btn-lg btn-danger" do %> Cancel
				<% end %>
		</center>
    <% end %>
  </div>
</div>

app/views/parts/add_hd.html.erb
<% provide(:title, 'Add A HD') %>

<center><h1>Add A HD</h1></center>
<center><%= image_tag("hd.png") %></center>
<center><p>-Hard Disk Drive-</p></center>
<center><p>A data storage device used for storing and retrieving digital information using rapidly rotating disks coated with magnetic material.</p></center>

<div class="row center jumbotron" >
  <div class="col-md-4 col-md-offset-4">

		<%= form_for :hd do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control',:placeholder => "Name" %>

		<%= f.label :price , "Price ($)" %>
		<%= f.number_field :price, class: 'form-control',:placeholder => "$ 0" %>

		<%= f.label :size, "Size (GB)" %>
		<%= f.number_field :size, class: 'form-control',:placeholder => "0 GB" %>

		<%= f.label :mb_compad, "Motherboard Compatability" %>
		<%= f.radio_button :mb_compad, "SATA 6.0 Gb/s", class: 'form-control' %>	<center><%= label_tag :mb_compad_SATA_6, "SATA 6.0 Gb/s" %></center>
		<%= f.radio_button :mb_compad, "SATA 3.0 Gb/s", class: 'form-control' %>	<center><%= label_tag :mb_compad_SATA_3, "SATA 3.0 Gb/s" %></center>
		<%= f.radio_button :mb_compad, "SAS 6.0 Gb/s", class: 'form-control' %>	<center><%= label_tag :mb_compad_SAS_6, "SAS 6.0 Gb/s" %></center>

		<%= f.label :watts %>
		<%= f.number_field :watts, class: 'form-control',:placeholder => "0" %>

		<br/>
		<br/>
		<center>
				<%= f.submit "Create HD", class: "btn btn-lg btn-success" %>
				<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
				<%= link_to parts_add_path, class: "btn btn-lg btn-danger" do %> Cancel
				<% end %>
		</center>
    <% end %>
  </div>
</div>

app/views/parts/add_motherboard.html.erb
<% provide(:title, 'Add A Motherboard') %>

<center><h1>Add A Motherboard</h1></center>
<br>
<center><%= image_tag("motherboard.png") %></center>
<br>
<center><p>The main printed circuit board found in computers.</p></center>
<center><p>It holds many of crucial electronic components of the system.</p></center>

<div class="row center jumbotron" >
  <div class="col-md-4 col-md-offset-4">

		<%= form_for :motherboard do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control',:placeholder => "Name" %>

		<%= f.label :price , "Price ($)" %>
		<%= f.number_field :price, class: 'form-control',:placeholder => "0" %>

		<%= f.label :cpu_compad, "CPU Compatability" %>
		<%= f.radio_button :cpu_compad, "AMD", class: 'form-control' %>	<center><%= label_tag :cpu_compad_amd, "AMD" %></center>
		<%= f.radio_button :cpu_compad, "Intel", class: 'form-control' %> <center><%= label_tag :cpu_compad_intel, "Intel" %></center>

		<%= f.label :gpu_compad, "GPU Compatability" %>
		<%= f.radio_button :gpu_compad, "PCI 3.0", class: 'form-control' %>	<center><%= label_tag :gpu_compad_pci_3, "PCI 3.0" %></center>
		<%= f.radio_button :gpu_compad, "PCI 3.0 x16", class: 'form-control' %>	<center><%= label_tag :gpu_compad_pci_3_16, "PCI 3.0 x16" %></center>
		<%= f.radio_button :gpu_compad, "PCI 2.0 x16", class: 'form-control' %>	<center><%= label_tag :gpu_compad_pci_2_16, "PCI 2.0 x16" %></center>

		<%= f.label :ram_compad, "RAM Compatability" %>
		<%= f.radio_button :ram_compad, "288-pin DDR4", class: 'form-control' %> <center><%= label_tag :ram_compad_288_DDR4, "288-pin DDR4" %></center>
		<%= f.radio_button :ram_compad, "240-pin DDR3", class: 'form-control' %> <center><%= label_tag :ram_compad_240_DDR3, "240-pin DDR3" %></center>
		<%= f.radio_button :ram_compad, "240-pin DDR2", class: 'form-control' %> <center><%= label_tag :ram_compad_240_DDR2, "240-pin DDR2" %></center>

		<%= f.label :hd_compad, "HD Compatability" %>
		<%= f.radio_button :hd_compad, "SATA 6.0 Gb/s", class: 'form-control' %> <center><%= label_tag :hd_compad_SATA_6, "SATA 6.0 Gb/s" %></center>
		<%= f.radio_button :hd_compad, "SATA 3.0 Gb/s", class: 'form-control' %> <center><%= label_tag :hd_compad_SATA_3, "SATA 3.0 Gb/s" %></center>
		<%= f.radio_button :hd_compad, "SAS 6.0 Gb/s", class: 'form-control' %> <center><%= label_tag :hd_compad_SAS_6, "SAS 6.0 Gb/s" %></center>

		<%= f.label :watts %>
		<%= f.number_field :watts, class: 'form-control',:placeholder => "0" %>


		<br/>
		<br/>
		<center>
				<%= f.submit "Create Motherboard", class: "btn btn-lg btn-success" %>
				<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
				<%= link_to parts_add_path, class: "btn btn-lg btn-danger" do %> Cancel
				<% end %>
		</center>
    <% end %>
  </div>
</div>

app/views/parts/add_power.html.erb
<% provide(:title, 'Add A Power Supply') %>

<center><h1>Add A Power Supply</h1></center>
<center><%= image_tag("power.png") %></center>
<center><p>The electronic device that supplies electric energy to an electrical load. </p></center>

<div class="row center jumbotron" >
  <div class="col-md-4 col-md-offset-4">

		<%= form_for :power do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control',:placeholder => "Name" %>

		<%= f.label :price , "Price ($)" %>
		<%= f.number_field :price, class: 'form-control',:placeholder => "0" %>

		<%= f.label :watts %>
		<%= f.number_field :watts, class: 'form-control',:placeholder => "0" %>

		<br/>
		<br/>
			<center>
				<%= f.submit "Create Power Supply", class: "btn btn-lg btn-success" %>
				<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
				<%= link_to parts_add_path, class: "btn btn-lg btn-danger" do %> Cancel
				<% end %>
			</center>
		</center>
    <% end %>
  </div>
</div>

app/views/parts/add_ram.html.erb
<% provide(:title, 'Add A RAM') %>

<center><h1>Add RAM</h1></center>
<center><%= image_tag("ram.png") %></center>
<center><p>-Random-Access Memory-</p></center>
<center><p> A form of computer data storage. </p></center>
<center><p> It allows data items to be read and written in roughly the same amount of time regardless of the order in which data items are accessed.</p></center>

<div class="row center jumbotron" >
  <div class="col-md-4 col-md-offset-4">

		<%= form_for :ram do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control',:placeholder => "Name" %>

		<%= f.label :price , "Price ($)" %>
		<%= f.number_field :price, class: 'form-control',:placeholder => "0" %>

		<%= f.label :size, "Size (GB)" %>
		<%= f.number_field :size, class: 'form-control',:placeholder => "0" %>

		<%= f.label :mb_compad, "Motherboard Compatability" %>
		<%= f.radio_button :mb_compad, "288-pin DDR4", class: 'form-control' %>	<center><%= label_tag :mb_compad_288_DDR4, "288-pin DDR4" %></center>
		<%= f.radio_button :mb_compad, "240-pin DDR3", class: 'form-control' %>	<center><%= label_tag :mb_compad_pci_240_DDR3, "240-pin DDR3" %></center>
		<%= f.radio_button :mb_compad, "240-pin DDR2", class: 'form-control' %>	<center><%= label_tag :mb_compad_pci_240_DDR3, "240-pin DDR2" %></center>

		<%= f.label :watts %>
		<%= f.number_field :watts, class: 'form-control',:placeholder => "0" %>

		<br/>
		<br/>
		<center>
				<%= f.submit "Create RAM", class: "btn btn-lg btn-success" %>
				<a>&nbsp&nbsp&nbsp&nbsp&nbsp</a>
				<%= link_to parts_add_path, class: "btn btn-lg btn-danger" do %> Cancel
				<% end %>
		</center>
    <% end %>
  </div>
</div>