config/routes.rb
CompApp::Application.routes.draw do
  get "blacklist_pages/blacklist"
  get "blacklist_pages/motherboard"
  get "blacklist_pages/cpu"
  get "blacklist_pages/ram"
  get "blacklist_pages/gpu"
  get "blacklist_pages/hd"
  get "blacklist_pages/power"
  get "blacklists/delete_mobo"
  get "blacklists/delete_cpu"
  get "blacklists/delete_ram"
  get "blacklists/delete_gpu"
  get "blacklists/delete_hd"
  get "blacklists/delete_power"
  post '/rate' => 'rater#create', :as => 'rate'
  get "computers/new"
  get "computers/current"
  get "computers/rename"
  get "computers/summary"
  get "computers/publish"
  get "computers/delete"

  get "similar_computers/menu"
  get "similar_computers/similar_price"
  get "similar_computers/similar_components"

  get "computers/delete_mobo"
  get "computers/delete_cpu"
  get "computers/delete_gpu"
  get "computers/delete_ram"
  get "computers/delete_hd"
  get "computers/delete_power"
  get "component_pages/cpu"
  get "component_pages/ram"
  get "component_pages/motherboard"
  get "build_by/price_option"
  get "build_by/select_price"
  post "build_by/select_price" => 'build_by#update'

  get "users/edit"
  get "users/new"
  get "users/index"
  get "component_pages/index"
  get "component_pages/gpu"
  get "component_pages/hd"
  get "component_pages/power"
  get "parts/add"
  get "parts/add_motherboard"
  post "parts/add_motherboard" => 'parts#create_motherboard'
  get "parts/add_cpu"
  post "parts/add_cpu" => 'parts#create_cpu'
  get "parts/add_gpu"
  post "parts/add_gpu" => 'parts#create_gpu'
  get "parts/add_ram"
  post "parts/add_ram" => 'parts#create_ram'
  get "parts/add_hd"
  post "parts/add_hd" => 'parts#create_hd'
  get "parts/add_power"
  post "parts/add_power" => 'parts#create_power'
  get "static_pages/home"
  get "static_pages/help"
  root "static_pages#home" #added this route to set the new home to static_pages#home
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :blacklists
  resources :users
  resources :computers

end

app/models/computer.rb
# == Schema Information
#
# Table name: computers
#
#  id         :integer          not null, primary key
#  name       :string(255)      name of the computer
#  status     :boolean          if the computer has all the required component, mark TRUE
#  price      :integer          Current total price
#  user_id    :integer          indicate which user the computer belongs to
#  created_at :datetime
#  updated_at :datetime
#

class Computer < ActiveRecord::Base

	attr_accessible :name, :status, :price, :user_id,
	 :hd_id, :motherboard_id, :ram_id, :gpu_id, :cpu_id, :power_id, :by_price
	belongs_to :user
	#validates :name, presence: true, length: { maximum: 59 }, uniqueness: { case_sensitive: false }
	#validates :status, presence: true
	#validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
	validates :user_id, presence: true
	#default_scope order: 'computers.created_at DESC'
	#before_save { |computer| computer.name = name.downcase }
	has_one :motherboard
	has_one :cpu
	has_one :gpu
	has_one :hd
	has_one :power
	has_one :ram
	ratyrate_rateable 'user_rating'
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  # before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]

  def rename
    @computer = Computer.find_by(id: current_user.current_comp)
  end

  def delete
    if logged_in?
      @computer = Computer.find_by_id(params[:id])
      if @computer.user_id == current_user.id
        if (@computer.id == current_user.current_comp)
          redirect_to root_url
          flash[:danger] = 'Cannot delete your current computer'
        end
        @computer.destroy
        redirect_to root_url
        flash[:success] = "Deleted your computer"
      else
        redirect_to root_url
        flash[:danger] = 'Can only delete your own computers'
      end
    else
      redirect_to root_url
      flash[:danger] = 'Must be logged in to do that'
    end
  end

  def summary
    @computer = Computer.find_by(id: current_user.current_comp)
    # if motherboard_id == nil

    @motherboard = Motherboard.find_by(id: @computer.motherboard_id)
    @cpu = Cpu.find_by(id: @computer.cpu_id)
    @ram = Ram.find_by(id: @computer.ram_id)
    @gpu = Gpu.find_by(id: @computer.gpu_id)
    @hd = Hd.find_by(id: @computer.hd_id)
    @power = Power.find_by(id: @computer.power_id)
    @sum_watts = (@motherboard.watts + @cpu.watts + @ram.watts + @gpu.watts + @hd.watts)*1.1
    @price_sum = (@motherboard.price + @cpu.price + @ram.price + @gpu.price + @hd.price)
  end

  def current
    if logged_in?
      @computer = Computer.find_by_id(params[:id])
      if @computer.user_id == current_user.id
        current_user.current_comp = @computer.id
        current_user.save(validate: false)
        redirect_to root_url
        flash[:success] = "Changed your current computer!"
      else
        redirect_to root_url
        flash[:danger] = 'Can only make your own Computers your Current Computer'
      end
    else
      redirect_to root_url
      flash[:danger] = 'Must be logged in to do that'
    end
  end

  def new
    if logged_in?
  	 @computer = Computer.new(user_id:current_user.id, price:0, hd_id:1, motherboard_id:1, ram_id:1,gpu_id:1,power_id:1,cpu_id:1, name:"default", by_price:99999)
     @computer.save
     current_user.current_comp = @computer.id
     current_user.save(validate: false)
     redirect_to build_by_price_option_path
    else
      redirect_to root_url
      flash[:danger] = 'Must be logged in to do that'
    end
  end

  def update
    @computer = Computer.find_by(id: current_user.current_comp)

    if @computer.update_attributes(computer_params)
      flash[:success] = 'Saved your selection!'
      redirect_to :back
    else
      flash[:danger] = 'We had a problem saving your part'
      redirect_to :back
    end
  end

  def publish #check motherboard and power supply when trying to publish/share
    @computer = Computer.find_by(id: current_user.current_comp)
    @motherboard = Motherboard.find_by(id: @computer.motherboard_id)
    @cpu = Cpu.find_by(id: @computer.cpu_id)
    @ram = Ram.find_by(id: @computer.ram_id)
    @gpu = Gpu.find_by(id: @computer.gpu_id)
    @hd = Hd.find_by(id: @computer.hd_id)
    @power = Power.find_by(id: @computer.power_id)
    @sum_watts = (@motherboard.watts + @cpu.watts + @ram.watts + @gpu.watts + @hd.watts)*1.1

    if @motherboard.cpu_compad != @cpu.mb_compad
      flash[:danger] = 'Motherboard and CPU do not match.'
      redirect_to :back
    elsif @motherboard.ram_compad != @ram.mb_compad
      flash[:danger] = 'Motherboard and RAM do not match.'
      redirect_to :back
    elsif @motherboard.gpu_compad != @gpu.mb_compad
      flash[:danger] = 'Motherboard and GPU do not match.'
      redirect_to :back
    elsif @motherboard.hd_compad != @hd.mb_compad
      flash[:danger] = 'Motherboard and HD do not match.'
      redirect_to :back
    elsif @power.watts < @sum_watts
      flash[:danger] = 'Power Supply cannot support.'
      redirect_to :back
    else
      #publish or share this computer here
    end

  end



  def delete_mobo
     @computer = Computer.find_by(id: current_user.current_comp)
     # @computer = Computer.find(params[:id])
    @computer.motherboard_id = 1
    if @computer.save
      flash[:success] = "Motherboard deleted."
      redirect_to computers_summary_path

    else
      flash[:danger] = 'Unable to delete.'
      redirect_to computers_summary_path
    end
  end

  def delete_cpu
     @computer = Computer.find_by(id: current_user.current_comp)
     # @computer = Computer.find(params[:id])
    @computer.cpu_id = 1
    if @computer.save
      flash[:success] = "CPU deleted."
      redirect_to computers_summary_path

    else
      flash[:danger] = 'Unable to delete.'
      redirect_to computers_summary_path
    end
  end

  def delete_gpu
     @computer = Computer.find_by(id: current_user.current_comp)
     # @computer = Computer.find(params[:id])
    @computer.gpu_id = 1
    if @computer.save
      flash[:success] = "GPU deleted."
      redirect_to computers_summary_path

    else
      flash[:danger] = 'Unable to delete.'
      redirect_to computers_summary_path
    end
  end

  def delete_ram
     @computer = Computer.find_by(id: current_user.current_comp)
     # @computer = Computer.find(params[:id])
    @computer.ram_id = 1
    if @computer.save
      flash[:success] = "RAM deleted."
      redirect_to computers_summary_path

    else
      flash[:danger] = 'Unable to delete.'
      redirect_to computers_summary_path
    end
  end

  def delete_hd
     @computer = Computer.find_by(id: current_user.current_comp)
     # @computer = Computer.find(params[:id])
    @computer.hd_id = 1
    if @computer.save
      flash[:success] = "HD deleted."
      redirect_to computers_summary_path

    else
      flash[:danger] = 'Unable to delete.'
      redirect_to computers_summary_path
    end
  end

  def delete_power
     @computer = Computer.find_by(id: current_user.current_comp)
     # @computer = Computer.find(params[:id])
    @computer.power_id = 1
    if @computer.save
      flash[:success] = "Power Supply deleted."
      redirect_to computers_summary_path

    else
      flash[:danger] = 'Unable to delete.'
      redirect_to computers_summary_path
    end
  end

  def create
  	@computer = current_user.computers.build(computer_params)


  	if @computer.save
      flash[:success] = 'Saved your selection!'
      redirect_to :back

  	else
      flash[:danger] = 'We had a problem saving your part.'
      redirect_to :back
  	end
  end



  private

  def computer_params
  	params.require(:computer).permit(:name, :status, :price, :hd_id, :motherboard_id, :ram_id, :gpu_id, :cpu_id, :power_id, :by_price )
  end
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/new.html.erb
<h1>Computers#new</h1>
<p>Find me in app/views/computers/new.html.erb</p>

app/views/computers/rename.html.erb
<% provide(:title, "Rename Computer") %>
<center><h1>Rename Your Computer</h1></center>

<div class="row center jumbotron">
	<div class="col-md-4 col-md-offset-4">
		<%= form_for(@computer) do |f| %> 
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
				<br>

				<div class="col-md-6 col-md-offset-3">
			<%= f.submit "Save changes", class: "btn btn-lg btn-primary" %>
				</div>
		<% end %>
	</div>
</div>

<p><center>Once you're done renaming your computer, click <%= link_to "here", static_pages_home_path %> to return to your home page.</center></p>

app/views/computers/summary.html.erb
  <% provide(:title, 'Summary') %>
  <center><h1><strong>Summary</strong></h1></center>
   <head>
          <script language="javascript">
              function turnRed() {
                  if(@motherboard.id = 1) {
                      document.getElementById("mobo").style.visibility="hidden";
                      document.getElementById("cont1").style.visibility="hidden";
                  }
              }
          </script>
      </head>
  <center>
    <body>
    <h2><center>Computer ID: <%= @computer.id %><br>
      Name: <%= @computer.name %><br>
    </center></h2>
    
      <br>
      <center><h3>Motherboard:  
      <%= link_to "Edit", component_pages_motherboard_path, class: "btn btn-primary btn-s" %>
      <%= link_to "Delete", computers_delete_mobo_path, data: {confirm: "Are you sure to delete?"}, class: "btn btn-primary btn-s disabled" %></h3></center>
       <table class="table">
        <tr class="active">
          <th><center>ID</center></th>
          <th><center>Name</center></th>
          <th><center>CPU Type</center></th>
          <th><center>GPU Type</center></th>
          <th><center>RAM Type</center></th>
          <th><center>HD Type</center></th>
          <th><center>Watts</center></th>
          <th><center>Price</center></th>
        </tr>
        <tr>
          <td><center><%= @motherboard.id %></center></td>
          <td><center><%= @motherboard.name %></center></td>
          <td><center><%= @motherboard.cpu_compad %></center></td>
          <td><center><%= @motherboard.gpu_compad %></center></td>
          <td><center><%= @motherboard.ram_compad %></center></td>
          <td><center><%= @motherboard.hd_compad %></center></td>
          <td><center><%= @motherboard.watts %></center></td>
          <td><center>$<%= @motherboard.price %></center></td>
        </tr>
      </table>

      <br>
      <center><h3>CPU:  
      <%= link_to "Edit", component_pages_cpu_path, class: "btn btn-primary btn-s" %>
      <%= link_to "Delete", computers_delete_cpu_path, data: {confirm: "Are you sure to delete?"}, class: "btn btn-primary btn-s" %></h3></center>
       <table class="table">
        <tr class="active">
          <th><center>ID</center></th>
          <th><center>Name</center></th>
          <th><center>Type</center></th>
          <th><center>Cores</center></th>
          <th><center>Speed</center></th>
          <th><center>Watts</center></th>
          <th><center>Price</center></th>
        </tr>
        <tr>
          <td><center><%= @cpu.id %></center></td>
          <td><center><%= @cpu.name %></center></td>
          <td><center><%= @cpu.mb_compad %></center></td>
          <td><center><%= @cpu.cores %></center></td>
          <td><center><%= @cpu.speed %> GHz</center></td>
          <td><center><%= @cpu.watts %></center></td>
          <td><center>$<%= @cpu.price %></center></td>
        </tr>
      </table>

      <br>
      <center><h3>GPU:  
      <%= link_to "Edit", component_pages_gpu_path, class: "btn btn-primary btn-s" %>
      <%= link_to "Delete", computers_delete_gpu_path, data: {confirm: "Are you sure to delete?"}, class: "btn btn-primary btn-s" %></h3></center>
       <table class="table">
        <tr class="active">
          <th><center>ID</center></th>
          <th><center>Name</center></th>
          <th><center>Type</center></th>
          <th><center>VRAM</center></th>
          <th><center>Watts</center></th>
          <th><center>Price</center></th>
        </tr>
        <tr>
          <td><center><%= @gpu.id %></center></td>
          <td><center><%= @gpu.name %></center></td>
          <td><center><%= @gpu.mb_compad %></center></td>
          <td><center><%= @gpu.vram %> GB</center></td>
          <td><center><%= @gpu.watts %></center></td>
          <td><center>$<%= @gpu.price %></center></td>
        </tr>
      </table>

      <br>
      <center><h3>RAM:  
      <%= link_to "Edit", component_pages_ram_path, class: "btn btn-primary btn-s" %>
      <%= link_to "Delete", computers_delete_ram_path, data: {confirm: "Are you sure to delete?"}, class: "btn btn-primary btn-s" %></h3></center>
       <table class="table">
        <tr class="active">
          <th><center>ID</center></th>
          <th><center>Name</center></th>
          <th><center>Type</center></th>
          <th><center>Size</center></th>
          <th><center>Watts</center></th>
          <th><center>Price</center></th>
        </tr>
        <tr>
          <td><center><%= @ram.id %></center></td>
          <td><center><%= @ram.name %></center></td>
          <td><center><%= @ram.mb_compad %></center></td>
          <td><center><%= @ram.size %> GB</center></td>
          <td><center><%= @ram.watts %></center></td>
          <td><center>$<%= @ram.price %></center></td>
        </tr>
      </table>

      <br>
      <center><h3>HD:  
      <%= link_to "Edit", component_pages_hd_path, class: "btn btn-primary btn-s" %>
      <%= link_to "Delete", computers_delete_hd_path, data: {confirm: "Are you sure to delete?"}, class: "btn btn-primary btn-s" %></h3></center>
       <table class="table">
        <tr class="active">
          <th><center>ID</center></th>
          <th><center>Name</center></th>
          <th><center>Type</center></th>
          <th><center>Size</center></th>
          <th><center>Watts</center></th>
          <th><center>Price</center></th>
        </tr>
        <tr>
          <td><center><%= @hd.id %></center></td>
          <td><center><%= @hd.name %></center></td>
          <td><center><%= @hd.mb_compad %></center></td>
          <td><center><%= @hd.size %> GB</center></td>
          <td><center><%= @hd.watts %></center></td>
          <td><center>$<%= @hd.price %></center></td>
        </tr>
      </table>

      <br>
      <center><h3>Power Supply:  
      <%= link_to "Edit", component_pages_power_path, class: "btn btn-primary btn-s" %>
      <%= link_to "Delete", computers_delete_power_path, data: {confirm: "Are you sure to delete?"}, class: "btn btn-primary btn-s" %></h3></center>
       <table class="table">
        <tr class="active">
          <th><center>ID</center></th>
          <th><center>Name</center></th>
          <th><center>Watts</center></th>
          <th><center>Price</center></th>
        </tr>
        <tr>
          <td><center><%= @power.id %></center></td>
          <td><center><%= @power.name %></center></td>
          <td><center><%= @power.watts %></center></td>
          <td><center>$<%= @power.price %></center></td>
        </tr>
      </table>
  </center>

<% if (@motherboard.cpu_compad != @cpu.mb_compad) %>
     <div class="alert alert-dismissable alert-danger">
<!--   <button type="button" class="close" data-dismiss="alert">×</button> -->
   <p><strong>Compatibility Error: </strong>Motherboard and CPU do not match. <strong><a class="alert-link"><%= link_to "Click to re-select.", component_pages_cpu_path%></a></strong></p>

</div>
<% end %>

<% if (@motherboard.ram_compad != @ram.mb_compad) %>
     <div class="alert alert-dismissable alert-danger">
<!--   <button type="button" class="close" data-dismiss="alert">×</button> -->
   <p><strong>Compatibility Error: </strong>Motherboard and RAM do not match. <strong><a class="alert-link"><%= link_to "Click to re-select.", component_pages_ram_path%></a></strong></p>

</div>
<% end %>


<% if (@motherboard.gpu_compad != @gpu.mb_compad) %>
     <div class="alert alert-dismissable alert-danger">
<!--   <button type="button" class="close" data-dismiss="alert">×</button> -->
   <p><strong>Compatibility Error: </strong>Motherboard and GPU do not match. <strong><a class="alert-link"><%= link_to "Click to re-select.", component_pages_gpu_path%></a></strong></p>

</div>
<% end %>

<% if (@motherboard.hd_compad != @hd.mb_compad) %>
     <div class="alert alert-dismissable alert-danger">
<!--   <button type="button" class="close" data-dismiss="alert">×</button> -->
  <p><strong>Compatibility Error: </strong>Motherboard and HD do not match. <strong><a class="alert-link"><%= link_to "Click to re-select.", component_pages_hd_path%></a></strong></p>

</div>
<% end %>

<% if (@power.watts < @sum_watts) %>
<div class="alert alert-dismissable alert-warning">
  <!-- <button type="button" class="close" data-dismiss="alert">×</button> -->
  <h4>Power Supply Error.</h4>
  <p>Power Supply cannot support.<a href="#" class="alert-link">Click to re-select.</a>.</p>
</div>
<% end %>

<% if (@computer.by_price != 99999) %>
  <div class="panel panel-default" align="center">
    <div class="panel-body">
    Total Build Price: $<%= @price_sum %>
    <br>
    Desired Max Build Price: $<%= @computer.by_price %>
    <br>
    <%= link_to "Change Max Price", build_by_select_price_path, class: "btn btn-large btn-info" %>
    </div>
  </div>
<% end %>


  <div>
    <center>
      <%= link_to static_pages_home_path, class: "btn btn-lg btn-primary" do %>
      <span class="glyphicon glyphicon-home"></span> Home
      <% end %>
    </center>
  </div>