config/routes.rb
CompApp::Application.routes.draw do
  get "blacklist_pages/blacklist"
  get "blacklist_pages/motherboard"
  get "blacklist_pages/cpu"
  get "blacklist_pages/ram"
  get "blacklist_pages/gpu"
  get "blacklist_pages/hd"
  get "blacklist_pages/power"
  get "blacklists/delete_mobo"
  get "blacklists/delete_cpu"
  get "blacklists/delete_ram"
  get "blacklists/delete_gpu"
  get "blacklists/delete_hd"
  get "blacklists/delete_power"
  post '/rate' => 'rater#create', :as => 'rate'
  get "computers/new"
  get "computers/current"
  get "computers/rename"
  get "computers/summary"
  get "computers/publish"
  get "computers/delete"

  get "similar_computers/menu"
  get "similar_computers/similar_price"
  get "similar_computers/similar_components"

  get "computers/delete_mobo"
  get "computers/delete_cpu"
  get "computers/delete_gpu"
  get "computers/delete_ram"
  get "computers/delete_hd"
  get "computers/delete_power"
  get "component_pages/cpu"
  get "component_pages/ram"
  get "component_pages/motherboard"
  get "build_by/price_option"
  get "build_by/select_price"
  post "build_by/select_price" => 'build_by#update'

  get "users/edit"
  get "users/new"
  get "users/index"
  get "component_pages/index"
  get "component_pages/gpu"
  get "component_pages/hd"
  get "component_pages/power"
  get "parts/add"
  get "parts/add_motherboard"
  post "parts/add_motherboard" => 'parts#create_motherboard'
  get "parts/add_cpu"
  post "parts/add_cpu" => 'parts#create_cpu'
  get "parts/add_gpu"
  post "parts/add_gpu" => 'parts#create_gpu'
  get "parts/add_ram"
  post "parts/add_ram" => 'parts#create_ram'
  get "parts/add_hd"
  post "parts/add_hd" => 'parts#create_hd'
  get "parts/add_power"
  post "parts/add_power" => 'parts#create_power'
  get "static_pages/home"
  get "static_pages/help"
  root "static_pages#home" #added this route to set the new home to static_pages#home
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :blacklists
  resources :users
  resources :computers

end

app/controllers/blacklist_pages_controller.rb
class BlacklistPagesController < ApplicationController
  def init_blacklist
    @motherbl = Blacklist.find_by(user_id: current_user).mobo_id.split(',')
    @cpubl = Blacklist.find_by(user_id: current_user).cpu_id.split(',')
    @rambl = Blacklist.find_by(user_id: current_user).ram_id.split(',')
    @gpubl = Blacklist.find_by(user_id: current_user).gpu_id.split(',')
    @hdbl = Blacklist.find_by(user_id: current_user).hd_id.split(',')
    @powerbl = Blacklist.find_by(user_id: current_user).power_id.split(',')
  end

  def blacklist
    init_blacklist
    @mobo = Motherboard.where(id: @motherbl)
    @cpu = Cpu.where(id: @cpubl)
    @ram = Ram.where(id: @rambl)
    @gpu = Gpu.where(id: @gpubl)
    @hd = Hd.where(id: @hdbl)
    @power = Power.where(id: @powerbl)
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @blacklist.save
  end

  def motherboard
    init_blacklist
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @mobo = Motherboard.where.not(id: @motherbl)
  end

  def cpu
    init_blacklist
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @cpu = Cpu.where.not(id: @cpubl)
  end

  def ram
    init_blacklist
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @ram = Ram.where.not(id: @rambl)
  end

  def gpu
    init_blacklist
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @gpu = Gpu.where.not(id: @gpubl)
  end

  def hd
    init_blacklist
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @hd = Hd.where.not(id: @hdbl)
  end

  def power
    init_blacklist
    @blacklist = Blacklist.find_by(user_id: current_user.id)
    @power = Power.where.not(id: @powerbl)
  end

end

app/helpers/blacklist_pages_helper.rb
module BlacklistPagesHelper
end

app/views/blacklist_pages/blacklist.html.erb
<% provide(:title, 'Blacklist') %>
<center><h1>Blacklist</h1></center>
<center><p>You can select parts that you do not wish to show up when you are building your computer.</p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li class="active">Blacklist</li>
</ul>
<center>
	<%= link_to blacklist_pages_motherboard_path, class: "btn btn-lg btn-primary" do %>
		<span class="glyphicon glyphicon-thumbs-down"></span> Motherboard
	<% end %>
	<%= link_to blacklist_pages_cpu_path, class: "btn btn-lg btn-primary" do %>
		<span class="glyphicon glyphicon-thumbs-down"></span> CPU
	<% end %>
	<%= link_to blacklist_pages_ram_path, class: "btn btn-lg btn-primary" do %>
		<span class="glyphicon glyphicon-thumbs-down"></span> RAM
	<% end %>
	<%= link_to blacklist_pages_gpu_path, class: "btn btn-lg btn-primary" do %>
		<span class="glyphicon glyphicon-thumbs-down"></span> GPU
	<% end %>
	<%= link_to blacklist_pages_hd_path, class: "btn btn-lg btn-primary" do %>
		<span class="glyphicon glyphicon-thumbs-down"></span> Hard Drive
	<% end %>
	<%= link_to blacklist_pages_power_path, class: "btn btn-lg btn-primary" do %>
		<span class="glyphicon glyphicon-thumbs-down"></span> Power Supply
	<% end %>
</center>
</div>

<center>
	<h3>Your Blacklisted Parts</h3>
	<br>
    	<center><h5>Motherboards</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>CPU Type</center></th>
            <th><center>GPU Type</center></th>
            <th><center>RAM Type</center></th>
            <th><center>HD Type</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @mobo.each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.cpu_compad %></td>
              <td><%= f.gpu_compad %></td>
              <td><%= f.ram_compad %></td>
              <td><%= f.hd_compad %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
              <td class="btn btn-primary btn-xs"><%= link_to "Delete", blacklists_delete_mobo_path(:moboid => f.id) %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>CPUs</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          </thead>
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>Cores</center></th>
            <th><center>Speed</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @cpu.drop(1).each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.cores %></td>
              <td><%= f.speed %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
              <td class="btn btn-primary btn-xs"><%= link_to "Delete", blacklists_delete_cpu_path(:cpuid => f.id) %></td>
            </tr>
          <% end %>
        </table>


        <center><h5>GPUs</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>VRAM</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @gpu.drop(1).each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.vram %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
              <td class="btn btn-primary btn-xs"><%= link_to "Delete", blacklists_delete_gpu_path(:gpuid => f.id) %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>RAM</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>Size</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @ram.drop(1).each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.size %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
              <td class="btn btn-primary btn-xs"><%= link_to "Delete", blacklists_delete_ram_path(:ramid => f.id) %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>HDs</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Type</center></th>
            <th><center>Size</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @hd.drop(1).each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.mb_compad %></td>
              <td><%= f.size %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
              <td class="btn btn-primary btn-xs"><%= link_to "Delete", blacklists_delete_hd_path(:hdid => f.id) %></td>
            </tr>
          <% end %>
        </table>

        <center><h5>Power Supplies</h5></center>
        <table class="table", style="width:80%;vertical-align:top">
          <tr class="active">
            <th><center>Name</center></th>
            <th><center>Watts</center></th>
            <th><center>Price</center></th>
          </tr>
          <% @power.drop(1).each do |f| %>
            <tr>
              <td><%= f.name %></td>
              <td><%= f.watts %></td>
              <td><%= f.price %></td>
              <td class="btn btn-primary btn-xs"><%= link_to "Delete", blacklists_delete_power_path(:powerid => f.id) %></td>
            </tr>
          <% end %>
        </table>
      </div>
  </center>
</html>

app/views/blacklist_pages/cpu.html.erb
<% provide(:title, 'CPU') %>
<center><h1>CPU</h1></center>
<center><p>-Central Processing Unit-</p></center>
<center><p>The hardware within a computer that carries out the instructions of a computer program.</p></center>
<center><p> It performs the basic arithmetical, logical, control and input/output operations of the system.</p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li><%= link_to "Blacklist", blacklist_pages_blacklist_path%></li>
  <li class="active">CPU Blacklist</li>
</ul>
<center>
  <table style="width:100%">
     <table class="table", style="width:80%;float:right;vertical-align:top">
      <tr class="active">
        <th></th>
        <th><center>ID</center></th>
        <th><center>Creator</center></th>
        <th><center>Name</center></th>
        <th><center>Type</center></th>
        <th><center>Cores</center></th>
        <th><center>Speed</center></th>
        <th><center>Watts</center></th>
        <th><center>Price</center></th>
      </tr>
</center>

  <%= form_for(@blacklist) do |cpubl_form| %>

    <% @cpu.drop(1).each do |f| %>
    <tr>
          <td><%= cpubl_form.radio_button :cpu_id, value = @blacklist.cpu_id + f.id.to_s + ','%></td>
          <td><%= f.id %></td>
          <% if f.creator != 0 %>
            <td><%= User.find_by(id: f.creator).name %></td>
          <% else %>
            <td>System</td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.mb_compad %></td>
          <td><%= f.cores %></td>
          <td><%= f.speed %> GHz</td>
          <td><%= f.watts %> Watts</td>
          <td>$<%= f.price %></td>
        </tr>
      <% end %>
  </table>
</table>
  <%= cpubl_form.submit "Blacklist", class: "btn btn-primary btn-lg btn-success" %>
  <%end%>

app/views/blacklist_pages/gpu.html.erb
<% provide(:title, 'GPU') %>
<center><h1>GPU</h1></center>
<center><p>-Graphics Processing Unit-</p></center>
<center><p>A specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer intended for output to a display. </p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li><%= link_to "Blacklist", blacklist_pages_blacklist_path%></li>
  <li class="active">GPU Blacklist</li>
</ul>
<center>
  <table style="width:100%">
     <table class="table", style="width:80%;float:right;vertical-align:top">
      <tr class="active">
        <th></th>
        <th><center>ID</center></th>
        <th><center>Creator</center></th>
        <th><center>Name</center></th>
        <th><center>Type</center></th>
        <th><center>VRAM</center></th>
        <th><center>Watts</center></th>
        <th><center>Price</center></th>
      </tr>
</center>

  <%= form_for(@blacklist) do |gpubl_form| %>

    <% @gpu.drop(1).each do |f| %>
    <tr>
          <td><%= gpubl_form.radio_button :gpu_id, value = @blacklist.gpu_id + f.id.to_s + ','%></td>
          <td><%= f.id %></td>
          <% if f.creator != 0 %>
            <td><%= User.find_by(id: f.creator).name %></td>
          <% else %>
            <td>System</td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.mb_compad %></td>
          <td><%= f.vram %> GB</td>
          <td><%= f.watts %> Watts</td>
          <td>$<%= f.price %></td>
        </tr>
      <% end %>
  </table>
</table>
  <%= gpubl_form.submit "Blacklist", class: "btn btn-primary btn-lg btn-success" %>
  <%end%>

app/views/blacklist_pages/hd.html.erb
<% provide(:title, 'HD') %>
<center><h1>HD</h1></center>
<center><p>-Hard Disk Drive-</p></center>
<center><p>A data storage device used for storing and retrieving digital information using rapidly rotating disks coated with magnetic material.</p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li><%= link_to "Blacklist", blacklist_pages_blacklist_path%></li>
  <li class="active">HD Blacklist</li>
</ul>
<center>
  <table style="width:100%">
     <table class="table", style="width:80%;float:right;vertical-align:top">
      <tr class="active">
        <th></th>
        <th><center>ID</center></th>
        <th><center>Creator</center></th>
        <th><center>Name</center></th>
        <th><center>Type</center></th>
        <th><center>Size</center></th>
        <th><center>Watts</center></th>
        <th><center>Price</center></th>
      </tr>
</center>

  <%= form_for(@blacklist) do |hdbl_form| %>

    <% @hd.drop(1).each do |f| %>
    <tr>
          <td><%= hdbl_form.radio_button :hd_id, value = @blacklist.hd_id + f.id.to_s + ','%></td>
          <td><%= f.id %></td>
          <% if f.creator != 0 %>
            <td><%= User.find_by(id: f.creator).name %></td>
          <% else %>
            <td>System</td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.mb_compad %></td>
          <td><%= f.size %></td>
          <td><%= f.watts %> Watts</td>
          <td>$<%= f.price %></td>
        </tr>
      <% end %>
  </table>
</table>
  <%= hdbl_form.submit "Blacklist", class: "btn btn-primary btn-lg btn-success" %>
  <%end%>

app/views/blacklist_pages/motherboard.html.erb
<% provide(:title, 'Motherboard') %>
<center><h1>Motherboard</h1></center>
<center><p>The main printed circuit board found in computers.</p></center>
<center><p>It holds many of crucial electronic components of the system.</p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li><%= link_to "Blacklist", blacklist_pages_blacklist_path%></li>
  <li class="active">Motherboard Blacklist</li>
</ul>
<center>
  <table style="width:100%">
     <table class="table", style="width:80%;float:right;vertical-align:top">
      <tr class="active">
        <th></th>
        <th><center>ID</center></th>
        <th><center>Creator</center></th>
        <th><center>Name</center></th>
        <th title="TEST"><center>CPU Type</center></th>
        <th><center>GPU Type</center></th>
        <th><center>RAM Type</center></th>
        <th><center>HD Type</center></th>
        <th><center>Watts</center></th>
        <th><center>Price</center></th>
      </tr>
</center>

  <%= form_for(@blacklist) do |mobobl_form| %>

    <% @mobo.drop(1).each do |f| %>
    <tr>
          <td><%= mobobl_form.radio_button :mobo_id, value = @blacklist.mobo_id + f.id.to_s + ',' %></td>
          <td><%= f.id %></td>
          <% if f.creator != 0 %>
            <td><%= User.find_by(id: f.creator).name %></td>
          <% else %>
            <td>System</td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.cpu_compad %></td>
          <td><%= f.gpu_compad %></td>
          <td><%= f.ram_compad %></td>
          <td><%= f.hd_compad %></td>
          <td><%= f.watts %> Watts</td>
          <td>$<%= f.price %></td>
        </tr>
      <% end %>
  </table>
</table>
  <%= mobobl_form.submit "Blacklist", class: "btn btn-primary btn-lg btn-success" %>
  <%end%>

app/views/blacklist_pages/power.html.erb
<% provide(:title, 'Power Supply') %>
<center><h1>Power Supply</h1></center>
<center><p>The electronic device that supplies electric energy to an electrical load. </p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li><%= link_to "Blacklist", blacklist_pages_blacklist_path%></li>
  <li class="active">Power Supply Blacklist</li>
</ul>
<center>
  <table style="width:100%">
     <table class="table", style="width:80%;float:right;vertical-align:top">
      <tr class="active">
        <th></th>
        <th><center>ID</center></th>
        <th><center>Creator</center></th>
        <th><center>Name</center></th>
        <th><center>Watts</center></th>
        <th><center>Price</center></th>
      </tr>
</center>

  <%= form_for(@blacklist) do |powerbl_form| %>

    <% @power.drop(1).each do |f| %>
    <tr>
          <td><%= powerbl_form.radio_button :power_id, value = @blacklist.power_id + f.id.to_s + ','%></td>
          <td><%= f.id %></td>
          <% if f.creator != 0 %>
            <td><%= User.find_by(id: f.creator).name %></td>
          <% else %>
            <td>System</td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.watts %> Watts</td>
          <td>$<%= f.price %></td>
        </tr>
      <% end %>
  </table>
</table>
  <%= powerbl_form.submit "Blacklist", class: "btn btn-primary btn-lg btn-success" %>
  <%end%>

app/views/blacklist_pages/ram.html.erb
<% provide(:title, 'RAM') %>
<center><h1>RAM</h1></center>
<center><p>-Random-Access Memory-</p></center>
<center><p> A form of computer data storage. </p></center>
<center><p> It allows data items to be read and written in roughly the same amount of time regardless of the order in which data items are accessed.</p></center>
<ul class="breadcrumb">
  <li><%= link_to "Home", static_pages_home_path%></li>
  <li><%= link_to "Blacklist", blacklist_pages_blacklist_path%></li>
  <li class="active">RAM Blacklist</li>
</ul>
<center>
  <table style="width:100%">
     <table class="table", style="width:80%;float:right;vertical-align:top">
      <tr class="active">
        <th></th>
        <th><center>ID</center></th>
        <th><center>Creator</center></th>
        <th><center>Name</center></th>
        <th><center>Type</center></th>
        <th><center>Size</center></th>
        <th><center>Watts</center></th>
        <th><center>Price</center></th>
      </tr>
</center>

  <%= form_for(@blacklist) do |rambl_form| %>

    <% @ram.drop(1).each do |f| %>
    <tr>
          <td><%= rambl_form.radio_button :ram_id, value = @blacklist.ram_id + f.id.to_s + ','%></td>
          <td><%= f.id %></td>
          <% if f.creator != 0 %>
            <td><%= User.find_by(id: f.creator).name %></td>
          <% else %>
            <td>System</td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.mb_compad %></td>
          <td><%= f.size %> GB</td>
          <td><%= f.watts %> Watts</td>
          <td>$<%= f.price %></td>
        </tr>
      <% end %>
  </table>
</table>
  <%= rambl_form.submit "Blacklist", class: "btn btn-primary btn-lg btn-success" %>
  <%end%>